constants:
  c: 299792458  # [m/s] speed of light
  k_B: 1.380649e-23  # [m^2 kg s-2 K-1]
  g_0: 9.81  # [m s-2] Gravity
  M_air: 28.97  # [g/mol] Molar mass of air
  R_0: 8.314459  # [J/mol/K] Universal gas constant
  N_A: 6.022e23  # [atoms / mol] Avogadro's number
  h: 6.626e-34  # [J s] Planck's constant
  G: 6.67430e-11  # [N m2 kg-2] Gravitational constant
  M_E: 5.97219e+24  # [kg] Earth's mass

params:
  # Thermodynamics
  L: 9.0  # [K/km] Temperature lapse rate for Denver
  P_0: 840  # [mbar] Typical absolute pressure for Denver
  T_0: 294.3  # [K] Typical 70 F temperature for Denver

  # Laser specs
  lamb_base: 822.5e-9  # [m] laser wavelength from Er:YAG
  freq_off: 2.0e+9  # [Hz] frequency offset for offline
  freq_on: 25.0e+9  # [Hz] frequency offset for online
  E_L: 6.0e-3  # [J] laser energy
  f_L: 2.0e+3  # [Hz] rep rate
  dt_L: 100.0e-9  # [s] laser pulse FWHM

  # Receiver specs
  D: 16  # [in] outer diameter of telescope
  d: 1.8  # [in] inner diameter of telescope
  R_eta: 0.7
  eta_QE: 0.5  # Detector quantum efficiency
  loss: 1  # Unaccounted loss term
  tD: 20.0e-9  # [s] SPAD deadtime
  dt_ABLE: 8.3e-9  # [s] native resolution of ABLE clock

  # Signal
  N_B: 0  # Number of background photons
  hres_ABLE: 75.0e+3  # [m] horizontal resolution ABLE
  vres_ABLE: 400.0  # [m] range resolution ABLE

  # Satellite
  orbit: 685.0e+3  # [m] altitude orbit (from CALIPSO)
  orbit_speed: 

